#!/usr/bin/env python3
import ast
from pathlib import Path

MODULE_ORDER = ("config.py", "tracker.py", "parser.py", "ui.py", "main.py")
PROJECT_ROOT = Path(__file__).resolve().parent
SRC_DIR = PROJECT_ROOT / "src"
OUT_FILE = PROJECT_ROOT / "rustdesk-monitor.py"
GENERATED_HEADER = '''#!/usr/bin/env python3
"""
RustDesk Connection Monitor v4.0
Generated from modular src/ files using build.py.
Do not edit this file directly; edit src/*.py and run build.py.
"""

'''


def _format_alias(alias):
    if alias.asname:
        return f"{alias.name} as {alias.asname}"
    return alias.name


def _format_import_from(node):
    module = "." * node.level + (node.module or "")
    names = ", ".join(_format_alias(alias) for alias in node.names)
    return f"from {module} import {names}"


def _is_bundled_import(node):
    """Return True for imports that are provided by another bundled src module."""
    return node.level == 0 and node.module and node.module.startswith("src")


def _collect_module(path, imports, blocks):
    code = path.read_text(encoding="utf-8")
    tree = ast.parse(code)

    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                imports.add(f"import {_format_alias(alias)}")
            continue

        if isinstance(node, ast.ImportFrom):
            # Imports from src.* are removed because those modules are concatenated
            # into the generated standalone script. Keep standard-library imports.
            if not _is_bundled_import(node):
                imports.add(_format_import_from(node))
            continue

        segment = ast.get_source_segment(code, node)
        if segment:
            blocks.append(segment)


def build():
    # Preserve module dependency order when concatenating source blocks.
    imports = set()
    blocks = []

    for module_name in MODULE_ORDER:
        _collect_module(SRC_DIR / module_name, imports, blocks)

    output = [GENERATED_HEADER]
    output.extend(f"{import_line}\n" for import_line in sorted(imports))
    output.append("\n")
    output.append("\n\n".join(blocks))
    output.append("\n")

    OUT_FILE.write_text("".join(output), encoding="utf-8")
    print(f"Successfully built {OUT_FILE.name}")


if __name__ == "__main__":
    build()
