#!/usr/bin/env python3
"""
RustDesk Connection Monitor v4.0
Generated from modular src/ files using build.py.
Do not edit this file directly; edit src/*.py and run build.py.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time

DEFAULT_DIRECT_PORT = "21118"

DEFAULT_CONFIG = {
    "direct_port": DEFAULT_DIRECT_PORT,
    "nat_type": 0,
    "rendezvous_server": "",
}

NAT_LABELS = {0: "Unknown", 1: "Asymmetric", 2: "Symmetric"}

SERVER_PORT_MAP = {
    "21114": {"type": "API Server", "color": "\033[1;35m"},
    "21116": {"type": "Rendezvous (Signaling)", "color": "\033[1;34m"},
    "21117": {"type": "Relay (Indirect Routing)", "color": "\033[1;31m"},
    "21118": {"type": "WS Rendezvous", "color": "\033[1;36m"},
    "21119": {"type": "WS Relay", "color": "\033[1;36m"},
}

def get_rustdesk_config_dir():
    xdg = os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
    candidates = [
        os.path.join(xdg, "rustdesk"),
        os.path.join(xdg, "RustDesk"),
        os.path.expanduser("~/.config/rustdesk"),
        os.path.expanduser("~/.config/RustDesk"),
    ]

    for path in candidates:
        if os.path.isdir(path):
            return path

    return os.path.join(xdg, "RustDesk")

def read_rustdesk_config():
    cfg = DEFAULT_CONFIG.copy()
    path = os.path.join(get_rustdesk_config_dir(), "RustDesk2.toml")

    if not os.path.isfile(path):
        return cfg

    try:
        with open(path, encoding="utf-8") as f:
            content = f.read()

        m = re.search(r"^nat_type\s*=\s*(\d+)", content, re.MULTILINE)
        if m:
            cfg["nat_type"] = int(m.group(1))

        m = re.search(
            r"^rendezvous_server\s*=\s*['\"]([^'\"]*)['\"]",
            content,
            re.MULTILINE,
        )
        if m:
            cfg["rendezvous_server"] = m.group(1)

        in_opts = False
        for line in content.splitlines():
            s = line.strip()

            if s == "[options]":
                in_opts = True
                continue

            if s.startswith("[") and s.endswith("]"):
                in_opts = False
                continue

            if in_opts:
                m = re.match(r"direct-access-port\s*=\s*['\"]?(\d+)['\"]?", s)
                if m and int(m.group(1)) > 0:
                    cfg["direct_port"] = m.group(1)
    except (OSError, ValueError) as e:
        print(f"Warning: failed to read config {path}: {e}", file=sys.stderr)

    return cfg

def compute_health(c):
    """A/B/C/D/F health grade from connection metrics."""
    if c.get("dir") == "LSTN":
        return "—"

    rtt = c.get("rtt")
    if rtt is None:
        return "?"

    retrans = c.get("retrans") or 0
    jitter = c.get("jitter") or 0

    try:
        q = int(c.get("rx", 0)) + int(c.get("tx", 0))
    except (ValueError, TypeError):
        q = 0

    if rtt < 20 and jitter < 5 and retrans == 0 and q == 0:
        return "A"
    if rtt < 50 and retrans <= 2:
        return "B"
    if rtt < 100:
        return "C"
    if rtt < 200:
        return "D"
    return "F"

def detect_alerts(conns):
    """Return list of alert strings for current state."""
    n_relay = n_rtt = n_retrans = n_queued = 0

    for c in conns:
        if "Relay" in c["type"] and c["dir"] != "LSTN":
            n_relay += 1

        rtt = c.get("rtt")
        if rtt is not None and rtt > 200:
            n_rtt += 1

        retrans = c.get("retrans")
        if retrans is not None and retrans > 5:
            n_retrans += 1

        try:
            if int(c.get("rx", 0)) > 0 or int(c.get("tx", 0)) > 0:
                n_queued += 1
        except (ValueError, TypeError):
            pass

    alerts = []
    if n_relay:
        alerts.append(f"⚠ {n_relay} relay connection(s) — not direct")
    if n_rtt:
        alerts.append(f"⚠ {n_rtt} connection(s) with RTT >200ms")
    if n_retrans:
        alerts.append(f"⚠ {n_retrans} connection(s) with retransmissions")
    if n_queued:
        alerts.append(f"⚠ {n_queued} connection(s) with queued data")

    return alerts

class ConnectionTracker:
    def __init__(self, spark_depth=20):
        self.spark_depth = spark_depth
        self._state = {}

    def _key(self, c):
        return (c["local"], c["peer"])

    def update(self, conns):
        now = time.time()
        seen = set()

        for c in conns:
            k = self._key(c)
            seen.add(k)

            if k not in self._state:
                self._state[k] = {
                    "first_seen": now,
                    "rtt_hist": [],
                    "prev_bsent": None,
                    "prev_brecv": None,
                    "prev_t": None,
                }

            st = self._state[k]
            c["duration"] = now - st["first_seen"]

            if c.get("rtt") is not None:
                st["rtt_hist"].append(c["rtt"])
                if len(st["rtt_hist"]) > self.spark_depth:
                    st["rtt_hist"] = st["rtt_hist"][-self.spark_depth :]

            c["rtt_hist"] = list(st["rtt_hist"])
            c["tx_rate"] = c["rx_rate"] = None

            bs = c.get("bytes_sent")
            br = c.get("bytes_received")
            if (
                bs is not None
                and st["prev_bsent"] is not None
                and st["prev_t"] is not None
            ):
                dt = now - st["prev_t"]
                if dt > 0.05:
                    c["tx_rate"] = max(0, bs - st["prev_bsent"]) / dt
                    c["rx_rate"] = max(0, br - (st["prev_brecv"] or 0)) / dt

            st["prev_bsent"] = bs
            st["prev_brecv"] = br
            st["prev_t"] = now

            c["health"] = compute_health(c)

        for k in [k for k in self._state if k not in seen]:
            del self._state[k]

        return conns

SS_COMMAND = ["ss", "-tuipn"]

_RE_RTT = re.compile(r"rtt:(\d+(?:\.\d+)?)/(\d+(?:\.\d+)?)")

_RE_CWND = re.compile(r"cwnd:(\d+)")

_RE_RETRANS = re.compile(r"retrans:\d+/(\d+)")

_RE_BSENT = re.compile(r"bytes_sent:(\d+)")

_RE_BRECV = re.compile(r"bytes_received:(\d+)")

_RE_PID = re.compile(r"pid=(\d+)")

_RE_PNAME = re.compile(r'users:\(\("([^"]+)"')

def extract_port(addr):
    if addr == "*:*" or addr.endswith(":*"):
        return "*"

    if "]:" in addr:
        return addr.rsplit(":", 1)[-1]

    if ":" in addr:
        return addr.rsplit(":", 1)[-1]

    return ""

def parse_tcp_info(line):
    rtt = jitter = cwnd = retrans = bsent = brecv = None

    m = _RE_RTT.search(line)
    if m:
        rtt = float(m.group(1))
        jitter = float(m.group(2))

    m = _RE_CWND.search(line)
    if m:
        cwnd = int(m.group(1))

    m = _RE_RETRANS.search(line)
    if m:
        retrans = int(m.group(1))

    m = _RE_BSENT.search(line)
    if m:
        bsent = int(m.group(1))

    m = _RE_BRECV.search(line)
    if m:
        brecv = int(m.group(1))

    return rtt, jitter, cwnd, retrans, bsent, brecv

def run_ss():
    try:
        return subprocess.check_output(
            SS_COMMAND,
            universal_newlines=True,
            stderr=subprocess.DEVNULL,
        )
    except FileNotFoundError:
        print(
            "\033[1;31mError:\033[0m 'ss' not found. Install iproute2.", file=sys.stderr
        )
        sys.exit(1)
    except subprocess.CalledProcessError:
        return ""

def parse_connections(process_name, direct_port):
    return parse_ss_output(run_ss(), process_name, direct_port)

def parse_ss_output(output, process_name, direct_port):
    conns = []
    lines = output.strip().split("\n")
    pname = process_name.lower()
    i = 0

    while i < len(lines):
        line = lines[i]
        if not _matches_process(line, pname):
            i += 1
            continue

        parts = line.split()
        if len(parts) < 6:
            i += 1
            continue

        tcp_info_line = None
        if _has_tcp_info_line(lines, i):
            tcp_info_line = lines[i + 1]
            i += 1

        conns.append(_parse_socket_parts(parts, tcp_info_line, direct_port))
        i += 1

    return conns

def _matches_process(line, process_name_lower):
    return process_name_lower in line.lower()

def _has_tcp_info_line(lines, index):
    return (
        index + 1 < len(lines)
        and lines[index + 1]
        and lines[index + 1][0] in (" ", "\t")
    )

def _parse_socket_parts(parts, tcp_info_line, direct_port):
    proto, state, rx, tx, local, peer = parts[:6]
    rtt = jitter = cwnd = retrans = bsent = brecv = None

    if tcp_info_line is not None:
        rtt, jitter, cwnd, retrans, bsent, brecv = parse_tcp_info(tcp_info_line)

    local_port = extract_port(local)
    peer_port = extract_port(peer)
    direction, conn_type, color = classify_connection(
        proto,
        state,
        local_port,
        peer_port,
        direct_port,
    )
    pid, pname = parse_process_info(parts[6:])

    return {
        "proto": proto,
        "state": state,
        "rx": rx,
        "tx": tx,
        "dir": direction,
        "local": local,
        "peer": peer,
        "pid": pid,
        "pname": pname,
        "type": conn_type,
        "color": color,
        "rtt": rtt,
        "jitter": jitter,
        "cwnd": cwnd,
        "retrans": retrans,
        "bytes_sent": bsent,
        "bytes_received": brecv,
    }

def classify_connection(proto, state, local_port, peer_port, direct_port):
    if state in ("LISTEN", "UNCONN"):
        return _classify_listener(local_port, direct_port)

    if local_port == direct_port and state == "ESTAB":
        return "IN", "Direct (Incoming Peer)", "\033[1;32m"

    if peer_port in SERVER_PORT_MAP:
        server = SERVER_PORT_MAP[peer_port]
        return "OUT", server["type"], server["color"]

    if proto == "udp" and peer_port not in ("*", ""):
        return "P2P", "Direct (UDP Hole-Punch)", "\033[1;32m"

    conn_type = "Direct (TCP P2P)" if proto == "tcp" else "Unknown"
    color = "\033[1;32m" if proto == "tcp" else "\033[0m"
    return "P2P", conn_type, color

def _classify_listener(local_port, direct_port):
    if local_port == direct_port:
        return "LSTN", "Direct Access (Listening)", "\033[1;32m"

    if local_port == "21116":
        return "LSTN", "Rendezvous (Listening)", "\033[1;34m"

    if local_port == "21118" and local_port != direct_port:
        return "LSTN", "WS Rendezvous (Listening)", "\033[1;36m"

    return "LSTN", "Service (Listening)", "\033[38;5;245m"

def parse_process_info(proc_parts):
    proc_blob = "".join(proc_parts) if proc_parts else ""
    pid = ""
    pname = ""

    m_pid = _RE_PID.search(proc_blob)
    if m_pid:
        pid = m_pid.group(1)

    m_pname = _RE_PNAME.search(proc_blob)
    if m_pname:
        pname = m_pname.group(1)

    return pid, pname

ANSI_RE = re.compile(r"\033\[[0-9;]*m")

SPARK_CHARS = "▁▂▃▄▅▆▇█"

R = "\033[0m"

B = "\033[1m"

DIM = "\033[38;5;242m"

BORDER = "\033[38;5;60m"

HDR_BG = "\033[48;5;236m\033[38;5;75m"

ALERT_BG = "\033[48;5;52m\033[38;5;196m"

LABEL = "\033[38;5;75m"

VAL = "\033[1;38;5;255m"

HEALTH_DOT = {
    "A": "\033[38;5;84m●",
    "B": "\033[38;5;114m●",
    "C": "\033[38;5;220m●",
    "D": "\033[38;5;208m●",
    "F": "\033[38;5;196m●",
    "?": "\033[38;5;242m○",
    "—": "\033[38;5;242m·",
}

DIR_ICONS = {
    "IN": "\033[38;5;84m▼",
    "OUT": "\033[38;5;75m▲",
    "P2P": "\033[38;5;183m⇄",
    "LSTN": "\033[38;5;242m◉",
    "?": "\033[38;5;242m·",
}

TYPE_COLORS = {
    "Direct": "\033[38;5;84m",
    "Relay": "\033[38;5;196m",
    "Rendezvous": "\033[38;5;75m",
    "API": "\033[38;5;183m",
    "WS": "\033[38;5;117m",
    "Service": "\033[38;5;242m",
}

def render_sparkline(values, width=10):
    if not values:
        return ""

    vals = values[-width:]
    lo = min(vals)
    hi = max(vals)
    span = hi - lo if hi > lo else 1
    out = ""

    for v in vals:
        idx = int((v - lo) / span * (len(SPARK_CHARS) - 1))
        out += SPARK_CHARS[min(idx, len(SPARK_CHARS) - 1)]

    return out

def rtt_color(rtt):
    if rtt is None:
        return "\033[38;5;242m"
    if rtt < 20:
        return "\033[38;5;84m"
    if rtt < 80:
        return "\033[38;5;220m"
    return "\033[38;5;196m"

def type_color(conn_type):
    for key, color in TYPE_COLORS.items():
        if key in conn_type:
            return color
    return "\033[0m"

def fmt_duration(secs):
    if secs < 60:
        return f"{int(secs)}s"
    if secs < 3600:
        return f"{int(secs // 60)}m{int(secs % 60)}s"

    h = int(secs // 3600)
    m = int((secs % 3600) // 60)
    return f"{h}h{m}m"

def fmt_rate(bps):
    if bps is None:
        return "—"
    if bps < 1024:
        return f"{bps:.0f}B"
    if bps < 1024 * 1024:
        return f"{bps / 1024:.1f}K"
    return f"{bps / 1024 / 1024:.1f}M"

def clear_screen():
    sys.stdout.write("\033[2J\033[H")
    sys.stdout.flush()

def ansi_len(s):
    return len(ANSI_RE.sub("", s))

def ansi_ljust(s, width):
    pad = width - ansi_len(s)
    if pad > 0:
        return s + (" " * pad)
    return s

def ansi_center(s, width):
    pad = width - ansi_len(s)
    if pad <= 0:
        return s

    left = pad // 2
    return " " * left + s + " " * (pad - left)

def trunc(s, w):
    if w <= 1:
        return ""

    mx = w - 1
    if len(s) <= mx:
        return s
    if mx < 10:
        return s[:mx]

    h = (mx - 3) // 2
    return s[:h] + "..." + s[-(mx - 3 - h) :]

def _border_line(tw, title="", char="─"):
    iw = tw - 2
    if not title:
        return f"{BORDER}├{char * iw}┤{R}"

    tlen = len(title) + 2
    pad = (iw - tlen - 2) // 2
    rem = iw - pad - tlen - 2
    return f"{BORDER}├{char * pad}┤{R} {B}{title}{R} {BORDER}├{char * rem}┤{R}"

def _boxed_line(tw, content):
    iw = tw - 4
    print(f"{BORDER}│{R} {ansi_center(content, iw)} {BORDER}│{R}")

def _stat_pill(label, value, color=VAL):
    return f"{LABEL}{label} {color}{value}{R}"

def _partition_connections(conns):
    active = [c for c in conns if c["dir"] != "LSTN"]
    infra = [c for c in conns if c["dir"] == "LSTN"]
    return active, infra

def _dashboard_dimensions(raw_tw, active):
    il = max([len(c["local"]) for c in active] + [5]) + 1 if active else 6
    ip = max([len(c["peer"]) for c in active] + [4]) + 1 if active else 5
    max_type = max([len(c["type"]) for c in active] + [16]) if active else 16

    fixed_cols_width = 3 + 5 + 4 + 8 + 11 + 12 + 15 + 8 + max_type
    needed_tw = fixed_cols_width + il + ip
    tw = min(raw_tw, max(110, needed_tw))

    return tw, il, ip, max_type

def _print_dashboard_header(tw):
    print(f"{BORDER}╭{'─' * (tw - 2)}╮{R}")

    clock = time.strftime("%H:%M:%S")
    title = "RustDesk Connection Monitor"
    title_s = f"{HDR_BG} {title} {R}"
    clock_s = f"{DIM}{clock}{R}"
    iw = tw - 4
    used = len(title) + 2 + len(clock)
    gap = iw - used
    left = gap // 2
    right = gap - left

    print(f"{BORDER}│{R} {' ' * left}{title_s}{' ' * right}{clock_s} {BORDER}│{R}")
    print(f"{BORDER}├{'─' * (tw - 2)}┤{R}")

def _connection_summary(active):
    direct_count = 0
    relay_count = 0
    rendezvous_count = 0
    rtts = []

    for c in active:
        ctype = c["type"]
        if "Direct" in ctype:
            direct_count += 1
        elif "Relay" in ctype:
            relay_count += 1
        elif "Rendezvous" in ctype:
            rendezvous_count += 1

        rtt = c.get("rtt")
        if rtt is not None:
            rtts.append(rtt)

    return direct_count, relay_count, rendezvous_count, rtts

def _print_summary(tw, active, nat_label, direct_port):
    direct_count, relay_count, rendezvous_count, rtts = _connection_summary(active)
    pills = [
        _stat_pill("Sessions:", str(len(active))),
        _stat_pill(
            "Direct:", str(direct_count), "\033[38;5;84m" if direct_count else VAL
        ),
        _stat_pill(
            "Relay:", str(relay_count), "\033[38;5;196m" if relay_count else VAL
        ),
        _stat_pill("Rend:", str(rendezvous_count)),
        _stat_pill("NAT:", nat_label),
    ]

    if rtts:
        avg = sum(rtts) / len(rtts)
        pills.append(_stat_pill("Avg RTT:", f"{avg:.1f}ms", rtt_color(avg)))

    _boxed_line(tw, "  │  ".join(pills))

    if direct_port != "21118":
        _boxed_line(tw, f"{DIM}Direct Port: {direct_port} (custom){R}")

def _print_alerts(tw, conns):
    alerts = detect_alerts(conns)
    if not alerts:
        return

    print(f"{BORDER}├{'─' * (tw - 2)}┤{R}")
    for alert in alerts:
        _boxed_line(tw, f"{ALERT_BG}{B} {alert} {R}")

def _active_layout(tw, il, ip, max_type):
    sp = 2
    hw = 3
    pw = 5
    dw = 4
    rttw = 11
    durw = 8
    type_min = max_type

    show_trend = tw >= 100
    show_throughput = tw >= 90
    spkw = 12 if show_trend else 0
    thrw = 15 if show_throughput else 0

    n_sp = 2 + (1 if show_trend else 0) + (1 if show_throughput else 0)
    fixed = hw + pw + dw + (sp * n_sp) + rttw + spkw + thrw + durw + type_min

    avail_addr = tw - fixed
    if il + ip <= avail_addr:
        lw = il
        prw = ip
    else:
        lw = avail_addr // 2
        prw = avail_addr - lw

    return {
        "sp": sp,
        "hw": hw,
        "pw": pw,
        "dw": dw,
        "rttw": rttw,
        "durw": durw,
        "show_trend": show_trend,
        "show_throughput": show_throughput,
        "spkw": spkw,
        "thrw": thrw,
        "lw": lw,
        "prw": prw,
    }

def _active_header(layout):
    sp = layout["sp"]
    hdr_parts = [
        f"{'':>{layout['hw']}}",
        f"{'PRT':<{layout['pw']}}",
        f"{'DIR':<{layout['dw']}}",
        f"{'':<{sp}}",
        f"{'LOCAL':<{layout['lw']}}",
        f"{'':<{sp}}",
        f"{'PEER':<{layout['prw']}}",
        f"{'':<{sp}}",
        f"{'RTT ms':<{layout['rttw']}}",
    ]

    if layout["show_trend"]:
        hdr_parts.append(f"{'TREND':<{layout['spkw']}}")

    if layout["show_throughput"]:
        hdr_parts.append(f"{'':<{sp}}")
        hdr_parts.append(f"{'THROUGHPUT':<{layout['thrw']}}")

    hdr_parts.append(f"{'AGE':<{layout['durw']}}")
    hdr_parts.append("TYPE")
    return "".join(hdr_parts)

def _rtt_text(c, color):
    if c.get("rtt") is not None:
        return f"{color}{c['rtt']:.1f}/{c['jitter']:.1f}{R}"
    return f"{DIM}—{R}"

def _trend_text(c, color, width):
    spark = render_sparkline(c.get("rtt_hist", []), width - 2)
    if spark:
        return f"{color}{spark}{R}"
    return f"{DIM}{'·' * (width - 2)}{R}"

def _throughput_text(c):
    if c.get("tx_rate") is not None:
        tx_r = fmt_rate(c["tx_rate"])
        rx_r = fmt_rate(c["rx_rate"])
        return f"\033[38;5;114m↑{tx_r}  \033[38;5;75m↓{rx_r}{R}"
    return f"{DIM}—{R}"

def _active_row(c, layout):
    sp = layout["sp"]
    color = rtt_color(c.get("rtt"))
    health = c.get("health", "?")
    health_dot = HEALTH_DOT.get(health, HEALTH_DOT["?"])
    dir_icon = DIR_ICONS.get(c["dir"], DIR_ICONS["?"])

    parts = [
        f" {health_dot}{R} ",
        f"{c['proto']:<{layout['pw']}}",
        ansi_ljust(f"{dir_icon}{R}", layout["dw"] + sp),
        f"{trunc(c['local'], layout['lw']):<{layout['lw']}}",
        f"{' ' * sp}",
        f"{trunc(c['peer'], layout['prw']):<{layout['prw']}}",
        f"{' ' * sp}",
        ansi_ljust(_rtt_text(c, color), layout["rttw"]),
    ]

    if layout["show_trend"]:
        parts.append(ansi_ljust(_trend_text(c, color, layout["spkw"]), layout["spkw"]))

    if layout["show_throughput"]:
        parts.append(f"{' ' * sp}")
        parts.append(ansi_ljust(_throughput_text(c), layout["thrw"]))

    dur_s = f"{DIM}{fmt_duration(c.get('duration', 0))}{R}"
    parts.append(ansi_ljust(dur_s, layout["durw"]))
    parts.append(f"{type_color(c['type'])}{c['type']}{R}")

    return "".join(parts)

def _print_active_table(tw, active, layout):
    print(f"  {DIM}{_active_header(layout)}{R}")
    print(f"  {BORDER}{'╌' * (tw - 4)}{R}")

    for c in active:
        print(_active_row(c, layout))

def _print_active_sessions(tw, active, il, ip, max_type):
    print(_border_line(tw, "Active Sessions"))
    print()

    layout = _active_layout(tw, il, ip, max_type)
    if active:
        _print_active_table(tw, active, layout)
        print()
        return

    empty_msg = f"{DIM}○  No active RustDesk sessions{R}"
    print(f"\n  {ansi_center(empty_msg, tw - 4)}\n")

def _print_infrastructure(tw, infra):
    print(_border_line(tw, "Infrastructure"))
    if infra:
        for c in infra:
            port = extract_port(c["local"])
            proto_badge = f"{DIM}{c['proto'].upper()}{R}"
            tc = type_color(c["type"])
            print(
                f"    {HEALTH_DOT['—']}{R}  {proto_badge}:{LABEL}{port}{R}    "
                f"{tc}{c['type']}{R}"
            )
    else:
        print(f"    {DIM}No listening sockets{R}")

def _print_legend(tw):
    print(f"{BORDER}├{'─' * (tw - 2)}┤{R}")
    legend = (
        f"   {HEALTH_DOT['A']}{R} Excellent  "
        f"{HEALTH_DOT['B']}{R} Good  "
        f"{HEALTH_DOT['C']}{R} Fair  "
        f"{HEALTH_DOT['D']}{R} Poor  "
        f"{HEALTH_DOT['F']}{R} Bad"
        f"    {DIM}│{R}    "
        f"{DIR_ICONS['IN']}{R} In   "
        f"{DIR_ICONS['OUT']}{R} Out   "
        f"{DIR_ICONS['P2P']}{R} P2P   "
        f"{DIR_ICONS['LSTN']}{R} Listen"
    )
    print(legend)
    print(f"{BORDER}╰{'─' * (tw - 2)}╯{R}")

def print_dashboard(conns, nat_label, direct_port):
    raw_tw = shutil.get_terminal_size((120, 20)).columns
    active, infra = _partition_connections(conns)
    tw, il, ip, max_type = _dashboard_dimensions(raw_tw, active)

    _print_dashboard_header(tw)
    _print_summary(tw, active, nat_label, direct_port)
    _print_alerts(tw, conns)
    _print_active_sessions(tw, active, il, ip, max_type)
    _print_infrastructure(tw, infra)
    _print_legend(tw)

def build_arg_parser():
    desc = (
        "RustDesk Connection Monitor v4.0 — real-time dashboard with throughput,\n"
        "RTT sparklines, health grading, and connection tracking."
    )
    epilog = (
        "EXAMPLES:\n"
        "  %(prog)s                     Interactive dashboard\n"
        "  %(prog)s -j | jq             JSON snapshot\n"
        "  %(prog)s -j -w 1             NDJSON stream every 1s\n"
        "  %(prog)s -w 0.25             Fast 250ms refresh\n"
        "  %(prog)s --log conn.jsonl    Dashboard + append to log file\n"
        "  %(prog)s -p mydesk           Custom-branded client"
    )

    parser = argparse.ArgumentParser(
        description=desc,
        epilog=epilog,
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "-j",
        "--json",
        action="store_true",
        help="JSON output (single shot, or NDJSON with --watch)",
    )
    parser.add_argument(
        "-w",
        "--watch",
        type=float,
        metavar="SECS",
        help="Refresh interval (default: 0.5 for TTY)",
    )
    parser.add_argument(
        "-p",
        "--process-name",
        default="rustdesk",
        metavar="NAME",
        help="Process name to filter (default: rustdesk)",
    )
    parser.add_argument(
        "--log",
        metavar="FILE",
        help="Append NDJSON records to FILE alongside dashboard",
    )
    return parser

def parse_args(argv=None):
    return build_arg_parser().parse_args(argv)

def load_runtime_config():
    rd_cfg = read_rustdesk_config()
    direct_port = str(rd_cfg["direct_port"])
    nat_type = rd_cfg["nat_type"]

    if isinstance(nat_type, int):
        nat_label = NAT_LABELS.get(nat_type, "Unknown")
    else:
        nat_label = "Unknown"

    return direct_port, nat_label

def refresh_interval(watch):
    interval = watch if watch is not None else 0.5
    if interval < 0.1:
        interval = 0.1
    return interval

def open_log_file(path):
    if not path:
        return None

    try:
        return open(path, "a", buffering=1, encoding="utf-8")
    except IOError as e:
        print(f"Warning: cannot open log file: {e}", file=sys.stderr)
        return None

def export_connections(conns):
    export = []
    for c in conns:
        e = dict(c)
        e.pop("color", None)
        e.pop("rtt_hist", None)
        export.append(e)
    return export

def make_record(conns, nat_label, direct_port):
    return {
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "nat_type": nat_label,
        "direct_port": direct_port,
        "connections": export_connections(conns),
    }

def collect_connections(tracker, process_name, direct_port):
    return tracker.update(parse_connections(process_name, direct_port))

def run_json_once(args, tracker, nat_label, direct_port):
    conns = collect_connections(tracker, args.process_name, direct_port)
    print(json.dumps(make_record(conns, nat_label, direct_port), indent=2))
    sys.exit(0)

def run_json_watch(args, tracker, nat_label, direct_port, interval):
    try:
        while True:
            conns = collect_connections(tracker, args.process_name, direct_port)
            print(json.dumps(make_record(conns, nat_label, direct_port)), flush=True)
            time.sleep(interval)
    except KeyboardInterrupt:
        sys.exit(0)

def should_loop_dashboard(args):
    return args.watch is not None or sys.stdout.isatty()

def write_log_record(log_fh, conns, nat_label, direct_port):
    if not log_fh:
        return

    try:
        log_fh.write(json.dumps(make_record(conns, nat_label, direct_port)) + "\n")
    except IOError:
        pass

def run_dashboard(args, tracker, nat_label, direct_port, interval, log_fh):
    loop = should_loop_dashboard(args)

    try:
        while True:
            conns = collect_connections(tracker, args.process_name, direct_port)

            if loop and sys.stdout.isatty():
                clear_screen()

            print_dashboard(conns, nat_label, direct_port)
            write_log_record(log_fh, conns, nat_label, direct_port)

            if not loop:
                break

            print(f"{DIM}  Ctrl+C to exit  │  Refreshing every {interval}s{R}")
            time.sleep(interval)
    except KeyboardInterrupt:
        print("\nExiting…")
    finally:
        if log_fh:
            log_fh.close()

def main():
    args = parse_args()
    direct_port, nat_label = load_runtime_config()
    interval = refresh_interval(args.watch)
    tracker = ConnectionTracker()
    log_fh = open_log_file(args.log)

    if args.json and args.watch is None:
        run_json_once(args, tracker, nat_label, direct_port)

    if args.json and args.watch is not None:
        run_json_watch(args, tracker, nat_label, direct_port, interval)

    run_dashboard(args, tracker, nat_label, direct_port, interval, log_fh)

if __name__ == "__main__":
    main()
